/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        "secondary": "#0061a5",
        "on-secondary": "#ffffff",
        "secondary-container": "#0095f8",
        "on-secondary-container": "#002b4e",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3a0b00",
        "on-tertiary-container": "#ef4800",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#d2e4ff",
        "secondary-fixed-dim": "#9fcaff",
        "on-secondary-fixed": "#001d36",
        "on-secondary-fixed-variant": "#00497e",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59e",
        "on-tertiary-fixed": "#3a0b00",
        "on-tertiary-fixed-variant": "#852400",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        
        "trust-grey": "#F2F2F2",
        "brand-black": "#111111", 
        "footer-bg": "#EFEBE3",
        "accent-rose": "#FF6B8B",
        "accent-blue": "#0099FF",
        "accent-orange": "#FF4D00",
        "accent-purple": "#BF80FF",
        "accent-yellow": "#FFD700",
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "80px",
        
        "container-margin": "24px",
        "trust-band-padding": "40px",
        "section-gap": "80px",
        "grid-gutter": "16px"
      },
      fontFamily: {
        "display": ["var(--font-syne)"],
        "body": ["var(--font-be-vietnam-pro)"],
        "label": ["var(--font-space-grotesk)"],
        
        "label-caps": ["var(--font-space-grotesk)"],
        "headline-md": ["var(--font-syne)"],
        "headline-lg-mobile": ["var(--font-syne)"],
        "body-lg": ["var(--font-be-vietnam-pro)"],
        "body-md": ["var(--font-be-vietnam-pro)"],
        "headline-lg": ["var(--font-syne)"],
        "display-lg": ["var(--font-syne)"],
        "price-tag": ["var(--font-space-grotesk)"]
      },
      fontSize: {
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "price-tag": ["14px", { "lineHeight": "1", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
