/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface": "#ffffff",
        "surface-dim": "#dadada",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        "secondary": "#0061a5",
        "on-secondary": "#ffffff",
        "secondary-container": "#0095f8",
        "on-secondary-container": "#002b4e",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3a0b00",
        "on-tertiary-container": "#ef4800",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#ffffff",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "trust-grey": "#F2F2F2",
        "brand-black": "#111111", 
        "footer-bg": "#EFEBE3",
        "accent-rose": "#FF6B8B",
        "accent-blue": "#0099FF",
        "accent-orange": "#FF4D00",
        "accent-purple": "#BF80FF",
        "accent-yellow": "#FFD700",
      },
      fontFamily: {
        "display": ["ZalandoSansExpanded"],
        "body": ["GoogleSans-Regular"],
        "label": ["GoogleSans-Medium"],
        "label-caps": ["GoogleSans-Bold"],
        "headline-md": ["ZalandoSansExpanded"],
        "headline-lg-mobile": ["ZalandoSansExpanded"],
        "body-lg": ["GoogleSans-Regular"],
        "body-md": ["GoogleSans-Regular"],
        "headline-lg": ["ZalandoSansExpanded"],
        "display-lg": ["ZalandoSansExpanded"],
        "price-tag": ["GoogleSans-Bold"]
      },
    },
  },
  plugins: [],
}
